version: '2'
services:
  redis:
    image: stingar/redis:1.8
  mongodb:
    image: stingar/mongodb:1.8
  hpfeeds-bhr:
    build:
      context: .
    image: hpfeeds-bhr:latest
    env_file:
      - hpfeeds-bhr.env
    links:
      - redis:redis
      - mongodb:mongodb
