---
  pkgs:
    - gcc
    - git
    - mongodb

  pip_executable: pip2

  hpfeeds_bhr_logdir: /var/log/hpfeeds_bhr

  hpfeeds_bhr_dir: /opt

  hpfeeds_repo: https://github.com/CommunityHoneyNetwork/hpfeeds.git
  hpfeeds_version: master
  hpfeeds_dir: /srv
